---
title: "lab2"
author: "mgao05"
date: "February 9, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmap)
library(animation)
library(ggplot2)
library(dplyr)
library(pander)
```

## For Lab 02: Recreate the Random Walk gif in the attached Animations in R tutorial.
    

```{r random walk animation}

# random.walk <- cumsum(rnorm(100))
#   
# plot( random.walk, type="l", col="darkred", axes=F, xlab="", ylab="", main="Random Walk" )
# abline( h=0, lty=2, col="gray" )
# 
# 
# 
# 
# 
# dir.create("gifs")
# setwd("gifs")
# 
# 
# library( animation )
# library(magick)
# 
# saveGIF({
# x <- cumsum( rnorm(100) )
# y <- cumsum( rnorm(100) )
# 
# max.x <- max(x)
# min.x <- min(x)
# max.y <- max(y)
# min.y <- min(y)
# 
# par( ask=F )
# par( mar=c(2,2,3,1) )
# 
# for( i in 1:100 )
# {
#   plot( x[i], y[i], pch=19, cex=2, xlim=c(min.x,max.x), ylim=c(min.y,max.y)  )
# }
#   
# }, 
# 
# movie.name = "rando_walk.gif",   # name of your gif
# interval = 0.3,                  # controls the animation speed
# ani.width = 800,                 # size of the gif in pixels
# ani.height = 800 )               # size of the git in pixels
#above is two demensions animation, both x, y axes change, randow walk only changes randomly on y axes.See codes below.
#




random.walk <- cumsum(rnorm(100))

max.y <- max(random.walk)
min.y <- min(random.walk)

dir.create("gifs")
setwd("gifs")


# par( ask=T )
library(animation)

png( )   # START OF GIF FUNCTION



saveGIF({

for( i in 1:100 )
{
   
   plot(  random.walk[1:i], type="l", col="steelblue", axes=F, xlab="", ylab="", main="Random Walk",
          ylim=c(min.y,max.y), xlim=c(0,100) )
   abline( h=0, lty=2, col="gray" )

}


}, 
movie.name= "random_walk.gif", 
interval = 0.3,
ani.width = 1600,
ani.height = 800
)



dev.off()  # END OF GIF FUNCTION









  x <- cumsum(rnorm(100))
  y <- cumsum(rnorm(100))
  
  max.x <- max(x)
  min.x <- min(x)
  max.y <- max(y)
  min.y <- min(y)
  
  par( ask= T)
  par( MAR=C(2,2,3,1))
  for( i in 5:100 )
  {
    plot(x[i], y[i], pch=19, cex=2, xlim = c(min.x, max.x), ylim = c(min.y, max.y))
  }
  











```

